package com.youcode.entities;
// Generated 12 mar. 2021 à 02:37:21 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@PrimaryKeyJoinColumn(name = "id_user")
@Table(name = "admin")
public class Admin implements Serializable {


	private User user;

	public Admin() {
	}

	public Admin(User user) {
		this.user = user;
	}

	

	@ManyToOne
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
