package com.youcode.entities;
// Generated 12 mar. 2021 à 02:37:21 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "reservation")
public class Reservation implements java.io.Serializable {

	private Integer idReservation;
	private Student student;
	private Typereservation typereservation;
	private Date dateReservation;
	private boolean confirmation;

	public Reservation() {
	}

	public Reservation(Student student, Typereservation typereservation, Date dateReservation, boolean confirmation) {
		this.student = student;
		this.typereservation = typereservation;
		this.dateReservation = dateReservation;
		this.confirmation = confirmation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_reservation", unique = true, nullable = false)
	public Integer getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(Integer idReservation) {
		this.idReservation = idReservation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_student", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_typeReservation", nullable = false)
	public Typereservation getTypereservation() {
		return this.typereservation;
	}

	public void setTypereservation(Typereservation typereservation) {
		this.typereservation = typereservation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateReservation", nullable = false, length = 10)
	public Date getDateReservation() {
		return this.dateReservation;
	}

	public void setDateReservation(Date dateReservation) {
		this.dateReservation = dateReservation;
	}

	@Column(name = "confirmation", nullable = false)
	public boolean isConfirmation() {
		return this.confirmation;
	}

	public void setConfirmation(boolean confirmation) {
		this.confirmation = confirmation;
	}

}
