package com.youcode.entities;
// Generated 12 mar. 2021 à 02:37:21 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@PrimaryKeyJoinColumn(name = "id_user")
@Table(name = "student")
public class Student implements Serializable {


	private User user;
	
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Student() {
	}

	public Student(User user) {
		this.user = user;
	}

	public Student(User user, Set<Reservation> reservations) {
		this.user = user;
		this.reservations = reservations;
	}

	

	@ManyToOne
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@OneToMany(mappedBy = "student")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
