package com.youcode.entities;
// Generated 12 mar. 2021 à 02:37:21 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Typereservation generated by hbm2java
 */
@Entity
@Table(name = "typereservation", catalog = "reservation")
public class Typereservation implements Serializable {

	private Long idTypeReservation;
	private String typeReservation;
	private Date dateReservation;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Typereservation() {
	}

	public Typereservation(String typeReservation, Date dateReservation) {
		this.typeReservation = typeReservation;
		this.dateReservation = dateReservation;
	}

	public Typereservation(String typeReservation, Date dateReservation, Set<Reservation> reservations) {
		this.typeReservation = typeReservation;
		this.dateReservation = dateReservation;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_typeReservation", unique = true, nullable = false)
	public Long getIdTypeReservation() {
		return this.idTypeReservation;
	}
	

	public void setIdTypeReservation(Long idTypeReservation) {
		this.idTypeReservation = idTypeReservation;
	}

	@Column(name = "typeReservation", nullable = false, length = 150)
	public String getTypeReservation() {
		return this.typeReservation;
	}

	public void setTypeReservation(String typeReservation) {
		this.typeReservation = typeReservation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateReservation", nullable = false, length = 10)
	public Date getDateReservation() {
		return this.dateReservation;
	}

	public void setDateReservation(Date dateReservation) {
		this.dateReservation = dateReservation;
	}

	@OneToMany(mappedBy = "typereservation")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
