package com.youcode.entities;
// Generated 12 mar. 2021 à 02:37:21 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = "user")
public class User implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_user", unique = true, nullable = false)
	private Long idUser;
	private Role role;
	private String firstName;
	private String lastName;
	private String email;
	private int phone;
	private Date dateIncription;
	private String password;
	
	@OneToMany(mappedBy = "user")
	private Set<Admin> admins = new HashSet<Admin>(0);
	
	@OneToMany(mappedBy = "user")
	private Set<Student> students = new HashSet<Student>(0);

	public User() {
	}

	public User(Role role, String firstName, String lastName, String email, int phone, Date dateIncription,
			String password) {
		this.role = role;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.dateIncription = dateIncription;
		this.password = password;
	}

	public User(Role role, String firstName, String lastName, String email, int phone, Date dateIncription,
			String password, Set<Admin> admins, Set<Student> students) {
		this.role = role;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.dateIncription = dateIncription;
		this.password = password;
		this.admins = admins;
		this.students = students;
	}


	public Long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Long idUser) {
		this.idUser = idUser;
	}

	@ManyToOne
	@JoinColumn(name = "id_role", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "firstName", nullable = false, length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false)
	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateIncription", nullable = false, length = 10)
	public Date getDateIncription() {
		return this.dateIncription;
	}

	public void setDateIncription(Date dateIncription) {
		this.dateIncription = dateIncription;
	}

	@Column(name = "password", nullable = false, length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	
	public Set<Admin> getAdmins() {
		return this.admins;
	}

	public void setAdmins(Set<Admin> admins) {
		this.admins = admins;
	}

	
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
